### ISSUE TITLE
API is not working 

### ISSUE THREAD

**Issue by divyanshuintech** [mhshariatipour1378/Avatars-Placeholder#4]
I am writing to report an issue with the API endpoint available at https://avatar.iran.liara.run/public. It appears that the API is not functioning as expected. I have tried accessing it multiple times over the past few days, but I consistently encounter errors or receive no response.

As a developer relying on this API for my applications, this disruption is causing significant inconvenience and affecting my project's progress. Could you please investigate this issue as a matter of urgency and provide an estimated timeframe for when the API will be back up and running?

**Comment by mhshariatipour1378** [comment]
Sorry, I fixed the problem and now the service is available.
The reception of the service has surprised me 😊. Until next week, the problem will be completely solved by upgrading the server.

**Comment by femave** [comment]
Hi looks like the same problem as before
